export const INDUSTRY_CATEGORIES: string[] = [
  'Technology',
  'Finance & Banking',
  'Healthcare',
  'E-Commerce',
  'Media & Entertainment',
  'Consulting',
  'Education',
  'Manufacturing',
  'Real Estate',
  'Energy & Utilities',
  'Logistics',
  'Automotive',
  'Gaming',
  'Legal',
  'Government & Public Sector',
  'Non-profit',
  'Hospitality',
  'Agriculture',
  'Telecommunications',
  'Insurance',
]
